global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:8080"]
    metrics_path: "/actuator/prometheus"

  - job_name: "payment-service"
    static_configs:
      - targets: ["payment-service:8082"]
    metrics_path: "/actuator/prometheus"

  - job_name: "merchant-service"
    static_configs:
      - targets: ["merchant-service:8083"]
    metrics_path: "/actuator/prometheus"

  - job_name: "auth-service"
    static_configs:
      - targets: ["auth-service:8081"]
    metrics_path: "/actuator/prometheus"

  - job_name: "fraud-service"
    static_configs:
      - targets: ["fraud-service:8086"]
    metrics_path: "/actuator/prometheus"
